version: '3.8'

services:
  web:
    build:
      context: .
    environment:
      DB_HOSTNAME: db
    ports:
      - 4000:4000
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:14
    hostname: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    ports:
      - 5432:5432
